# Generated by Django 4.2 on 2023-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('bus_price', models.IntegerField()),
                ('train_price', models.IntegerField()),
                ('flight_price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='destination/')),
                ('image2', models.ImageField(upload_to='destination/')),
                ('image3', models.ImageField(upload_to='destination/')),
                ('image4', models.ImageField(upload_to='destination/')),
                ('food_price', models.IntegerField()),
                ('number_of_person', models.IntegerField()),
                ('days', models.CharField(max_length=30)),
                ('nights', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'destination_tb',
            },
        ),
    ]
