# Generated by Django 4.2 on 2023-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_email', models.CharField(max_length=30)),
                ('admin_password', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'admin_tb',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_phone', models.BigIntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_password', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
