# Generated by Django 4.2 on 2023-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
