# Generated by Django 4.2 on 2023-05-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_destination'),
        ('common', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_mode', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train'), ('flight', 'Flight')], max_length=100)),
                ('travel_food', models.BooleanField(default=False)),
                ('travel_date', models.DateField()),
                ('travel_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.destination')),
            ],
            options={
                'db_table': 'booking_tb',
            },
        ),
    ]
