# Generated by Django 4.2 on 2023-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='static/images/dummy-user.png', upload_to='customer/'),
        ),
    ]
